### ISSUE TITLE
Doesn't work with pip 1.2 or later

### ISSUE THREAD

**Issue by dpoirier** [jbalogh/vending-machine#4]
With pip 1.2.1:

```
[INFO] Creating vendor directory at /home/dpoirier/mozilla/basket15/vendor.
Traceback (most recent call last):
  File "/home/dpoirier/VE/basket15/bin/vend", line 7, in <module>
    execfile(__file__)
  File "/home/dpoirier/VE/basket15/src/vend/vend", line 222, in <module>
    args.func(args)
  File "/home/dpoirier/VE/basket15/src/vend/vend", line 52, in sync_command
    pip.version_control()
AttributeError: 'module' object has no attribute 'version_control'
```

With pip 1.3.1:

```
[INFO] Creating vendor directory at /home/dpoirier/mozilla/basket15/vendor.
Traceback (most recent call last):
  File "/home/dpoirier/VE/basket15/bin/vend", line 7, in <module>
    execfile(__file__)
  File "/home/dpoirier/VE/basket15/src/vend/vend", line 222, in <module>
    args.func(args)
  File "/home/dpoirier/VE/basket15/src/vend/vend", line 51, in sync_command
    pip.load_all_commands()
AttributeError: 'module' object has no attribute 'load_all_commands'
```
